[project]
name = 'Supply-Chain-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.high-value-items]
path = 'contracts/high-value-items.clar'
clarity_version = 2
epoch = 2.5

[contracts.iot-integration]
path = 'contracts/iot-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.product-registry]
path = 'contracts/product-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.verification-checkpoints]
path = 'contracts/verification-checkpoints.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
